import 'package:flutter/material.dart';

const categoryIconMap = <String, IconData>{
  'restaurant': Icons.restaurant_outlined,
  'cafe': Icons.local_cafe_outlined,
  'fastfood': Icons.fastfood_outlined,
  'bar': Icons.local_bar_outlined,
  'grocery': Icons.local_grocery_store_outlined,
  'car': Icons.directions_car_outlined,
  'bus': Icons.directions_bus_outlined,
  'taxi': Icons.local_taxi_outlined,
  'flight': Icons.flight_outlined,
  'bike': Icons.pedal_bike_outlined,
  'shopping': Icons.shopping_bag_outlined,
  'cart': Icons.shopping_cart_outlined,
  'store': Icons.storefront_outlined,
  'clothes': Icons.checkroom_outlined,
  'gift': Icons.redeem_outlined,
  'hospital': Icons.local_hospital_outlined,
  'fitness': Icons.fitness_center_outlined,
  'spa': Icons.spa_outlined,
  'medicine': Icons.medication_outlined,
  'health': Icons.health_and_safety_outlined,
  'games': Icons.sports_esports_outlined,
  'movie': Icons.movie_outlined,
  'music': Icons.music_note_outlined,
  'sports': Icons.sports_outlined,
  'celebration': Icons.celebration_outlined,
  'home': Icons.home_outlined,
  'electrical': Icons.electrical_services_outlined,
  'plumbing': Icons.plumbing_outlined,
  'cleaning': Icons.cleaning_services_outlined,
  'school': Icons.school_outlined,
  'book': Icons.menu_book_outlined,
  'computer': Icons.computer_outlined,
  'bank': Icons.account_balance_outlined,
  'savings': Icons.savings_outlined,
  'trending': Icons.trending_up_outlined,
  'credit': Icons.credit_card_outlined,
  'payments': Icons.payments_outlined,
  'work': Icons.work_outlined,
  'business': Icons.business_center_outlined,
  'money': Icons.attach_money_rounded,
  'tag': Icons.tag_outlined,
  'star': Icons.star_outline_rounded,
  'favorite': Icons.favorite_outline_rounded,
  'category': Icons.category_outlined,
  // legacy keys from default categories
  'utensils': Icons.restaurant_outlined,
  'heart': Icons.favorite_outline_rounded,
  'tv': Icons.movie_outlined,
  'shirt': Icons.checkroom_outlined,
  'zap': Icons.electrical_services_outlined,
  'briefcase': Icons.work_outlined,
  'laptop': Icons.computer_outlined,
};

IconData categoryIcon(String? key) =>
    categoryIconMap[key ?? 'tag'] ?? Icons.tag_outlined;
